services:
  - type: web
    name: metabase
    env: docker
    image:
      url: metabase/metabase:v0.49.17
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_DBNAME
        fromDatabase:
          name: metabase-db
          property: database
      - key: MB_DB_HOST
        fromDatabase:
          name: metabase-db
          property: host
      - key: MB_DB_PORT
        fromDatabase:
          name: metabase-db
          property: port
      - key: MB_DB_USER
        fromDatabase:
          name: metabase-db
          property: user
      - key: MB_DB_PASS
        fromDatabase:
          name: metabase-db
          property: password
databases:
  - name: metabase-db
    databaseName: metabase
    plan: free
