services:
  - type: web
    name: metabase
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    autoDeploy: true
    healthCheckPath: /
    buildCommand: echo "Build process handled by Dockerfile"
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_DBNAME
        fromDatabase:
          name: metabase-db
          property: database
      - key: MB_DB_HOST
        fromDatabase:
          name: metabase-db
          property: host
      - key: MB_DB_PORT
        fromDatabase:
          name: metabase-db
          property: port
      - key: MB_DB_USER
        fromDatabase:
          name: metabase-db
          property: user

      - key: MB_DB_PASS
        fromDatabase:
          name: metabase-db
          property: password
      - key: MB_JETTY_HOST
        value: 0.0.0.0
      - key: MB_JETTY_PORT
        value: 3000
      - key: JAVA_OPTS
        value: "-Xmx2g -XX:+UseG1GC -XX:+UseStringDeduplication"
      - key: MB_EDITION
        value: oss
      - key: NODE_ENV
        value: production

databases:
  - name: metabase-db
    databaseName: metabase
    plan: free
